# AUTOGENERATED! DO NOT EDIT! File to edit: ../lib_nbs/kalman/Random_Walker.ipynb.

# %% auto 0
__all__ = []

# %% ../lib_nbs/kalman/Random_Walker.ipynb 7
import numpy as np
import statsmodels.api as sm
from fastcore.basics import patch
